### ISSUE TITLE
roborazziの動きがおかしい

### ISSUE THREAD

**Issue by gen0083** [gen0083/android-engineer-codechechek#114]
PRによって変化している画像をコメントしてくれるが、その画像がおかしい
mainブランチの画像がうまく取得できていない？

そもそもなぜその画像（トップページで検索後の画像）になってるのかも謎
ComposeTestSampleによる画像が出力されていると思われるが・・・

**Comment by gen0083** [comment]
おそらく直ってない・・・比較元が常に空っぽだ
Actionsの方がなんか足りてないか見直してみるか・・・

**Comment by gen0083** [comment]
mainブランチでrecordRoborazziDebugを実行して保存された画像をアップロードしておく
pull_requestでcompareRoborazziDebugを実行すると保存された画像との比較を行う仕組み
ローカルでは確認ができた

commentが正しく行われないのは、
- mainブランチでstoreが正しく行われていない
- mainブランチでアップロードが正しく行われていない
- 各PRでアップロードされた画像をダウンロードできていない

が考えられる

ローカルで既存画像なしでcompareした際の結果が今の結果と一緒なので、そのあたりを中心に調べてみよう

**Comment by takahirom** [comment]
試していただいてありがとうございます。 mainからダウンロードできていないみたいですね 👀 
よくあるのはmainでビルド中だとダウンロードできないというもので、 lewagon/wait-on-check-action とかを使うと、mainでのビルドを待てたりします
https://github.com/gen0083/android-engineer-codechechek/actions/runs/9515613682/job/26239815993
<img width="856" alt="image" src="https://github.com/gen0083/android-engineer-codechechek/assets/1386930/b9ef24bc-5b6b-490d-8926-390de4964916">

**Comment by gen0083** [comment]
コメントありがとうございます
GitHub Actionsの設定は手探り状態なのでありがたいです 🙏 
試してみます

**Comment by gen0083** [comment]
どうやらようやく正しく比較できるようになったようだ
- #128 

コメントの検索がうまく動いてないけど・・・
